# Vendor Stan functions from primarycensored into epinowcast
#
# Regenerates inst/stan/functions/primarycensored.stan from the installed
# primarycensored package using primarycensored::pcd_load_stan_functions(),
# mirroring the approach EpiNow2 uses
# (https://github.com/epiforecasts/EpiNow2/blob/main/inst/dev/vendor-primarycensored.R).
#
# Run from the package root:
#   Rscript inst/dev/vendor-primarycensored.R
#
# The companion workflow .github/workflows/check-primarycensored.yaml runs this
# weekly and opens a pull request when the vendored copy is out of date.

library(primarycensored)

output_file <- "inst/stan/functions/primarycensored.stan"

# epinowcast discretises the parametric reference delay with
# primarycensored_sone_lpmf_vectorized() (see primarycensored_pmf.stan).
# primarycensored_ode, dist_lcdf, primary_lpdf and expgrowth_lpdf are passed by
# reference (e.g. to ode_rk45) so the dependency resolver does not detect them
# automatically; list them explicitly, as EpiNow2 does.
funcs <- c(
  "primarycensored_sone_lpmf_vectorized",
  "primarycensored_ode",
  "dist_lcdf",
  "primary_lpdf",
  "expgrowth_lpdf"
)

invisible(pcd_load_stan_functions(
  functions = funcs,
  dependencies = TRUE,
  write_to_file = TRUE,
  output_file = output_file
))

# pcd_load_stan_functions() writes a one-line provenance header recording the
# primarycensored version. Prepend an epinowcast attribution/licence note and
# transliterate the few non-ASCII characters in the upstream doc comments to
# ASCII: enw_stan_to_r() concatenates every inst/stan/functions/*.stan file into
# a single Stan program, and some stanc versions raise a lexing error on
# non-ASCII bytes in that combined block.
version <- as.character(packageVersion("primarycensored"))

lines <- readLines(output_file, encoding = "UTF-8", warn = FALSE)
# Transliterate Greek letters used in the log_weibull_g documentation.
lines <- gsub("λ", "lambda", lines, perl = TRUE) # lambda
lines <- gsub("γ", "lower_gamma", lines, perl = TRUE) # gamma
# Drop any remaining non-ASCII bytes (defensive; should be none after the
# substitutions above).
lines <- iconv(lines, from = "UTF-8", to = "ASCII", sub = "")

header <- c(
  "/**",
  " * Vendored primary event censored distribution functions",
  " *",
  " * AUTO-GENERATED by inst/dev/vendor-primarycensored.R from the installed",
  paste0(
    " * primarycensored package (version ", version, "), part of the"
  ),
  " * epinowcast organisation: https://github.com/epinowcast/primarycensored",
  " * (https://primarycensored.epinowcast.org). Do not edit by hand; rerun the",
  " * vendoring script instead.",
  " *",
  " * These functions implement the double interval censoring discretisation",
  " * used by epinowcast's parametric reference delay model (a continuous delay",
  " * convolved with a uniform primary event window, interval censored on the",
  " * secondary side, with optional right truncation).",
  " *",
  " * primarycensored is distributed under the MIT licence (Copyright (c) 2024",
  " * primarycensored authors), reproduced in",
  " * inst/stan/functions/LICENSE.primarycensored. Both primarycensored and",
  " * epinowcast are MIT licensed and maintained by the epinowcast",
  " * organisation.",
  " *",
  " * Note: a few non-ASCII characters in upstream doc comments (the Greek",
  " * letters lambda and gamma) are transliterated to ASCII by the vendoring",
  " * script so the concatenated functions block lexes on all stanc versions.",
  " */",
  ""
)

writeLines(c(header, lines), output_file)

deps <- unique(unlist(lapply(funcs, pcd_stan_function_deps)))
cat(
  "Vendored", length(deps), "Stan functions from primarycensored",
  version, "\n"
)
cat("Functions:", paste(deps, collapse = ", "), "\n")
cat("Written to:", output_file, "\n")
