---
title: Model definition and implementation
author: Sam Abbott
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Model definitions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```


In the following sections we provide methodological and implementation details for the nowcasting framework implemented in `epinowcast`. Our approach is an extension of that proposed by Günther et al. which was itself an extension of the model proposed by Höhle and Heiden and implemented in the `surveillance` R package. `epinowcast` adds an optional parametric assumption for the underlying delay from occurance to report, support for jointly nowcasting multiple related datasets, a flexible formula interface allowing for the specification of a large range of models, and an efficient implementation in `stan` which makes use of within chain parallisation to reduce runtimes when more cores than MCMC chains are available.

# Decomposition into expected final notifications and report delay components

We follow the approach of Höhle and Heiden and consider the distribution of notifications ($n_{gtd}$) by time of occurrence ($t$) and reporting delay ($d$) conditional on the final observed count $N_{gt}$ for each dataset ($g$) such that,

\begin{equation}
  N_{gt} = \sum_{d=0}^{D} n_{gtd}
\end{equation}

where $D$ represents the maximum delay between time of occurance and time of report which in theory could be infinite but in practice we set to a value in order to make the model identifiable and computationally feasible. This formulation means that $n_{gtd} \mid N_{gt}$ is multinomial with a probability vector ($p_{gtd}$) of length $D$ for each $t$ and $g$ that needs to be estimated at the same time as estimating the expected number of final notifications $\mathbb{E}[N_{gt}] = \lambda_{gt}$.

An alternative approach, not explored here, is to consider each $n_{gtd}$ independently at which point the model can be defined as a standard regression with the appropriate observation model and adjustment for reporting delay (i.e it becomes a Poisson or Negative Binomial regression). An implementation of this approach is available in . More work needs to be done to evaluate which of these approaches produces more accurate nowcasts for epidemiological count data.

# Expected final notifications

Here we follow the approach of Günther et al. and specify the model for expected final notifications as a first order random walk based on the findings of McGough, Johansson, Lipsitch, and Menzies. This model can in principle be any model such as a more complex time-series appproach, a gaussian process, or a mechanistic or semi-mechanistic compartmental model. Extending the flexibility of this model is an area of further work as is evaluating the benefits and tradeoffs of more complex approaches.

\begin{align}
  \log (\lambda_{gt}) &\sim \text{Normal}\left(\log (\lambda_{gt-1}) , \sigma^{\lambda}_{g} \right) \\
  \log (\lambda_{g0}) &\sim \text{Normal}\left(\log (N_{g0}), 1 \right) \\ \sigma^{\lambda}_{g} &\sim \text{Half-Normal}\left(0, 1\right)
\end{align}

# Delay distribution

Again following the approach of Günther et al. we define the delay distribution ($p_{gtd}$) as a discrete time hazard model ($h_{gtd} =\text{P} \left(\text{delay}=d|\text{delay} \geq d, W_{gtd}\right)$) but we extend this model to decompose $W_{gtd}$ into 3 components: hazard derived from a parametric delay distribution ($\gamma_{gtd}$) dependent on covariates at the date of occurance, hazard not derived from a parametric distribution ($\delta_{gtd}$) dependent on covariates at the date of occurance, and hazard dependent on covariates referenced to the date of report ($\epsilon_{gtd}$).

For first component ($\gamma_{gtd}$) we assume that the probability of reporting $p^{\prime}_{gtd}$ given parametric effects on the reference day only follow a parametric distribution (in the baseline case a discretised log normal distribution) with the log mean and log standard deviation being defined using an intercept and arbitrary shared covariates with fixed ($\alpha_{i}$) and random ($\beta_{i}$) coefficients,

\begin{align}
  p^{\prime}_{gtd} &\sim \text{LogNormal} \left(\mu_{gt}, \upsilon_{gt} \right) \\
  \mu_{gt} &= \mu_0 + \alpha_{\mu} X_{\gamma} + \beta_{\mu} Z_{\gamma} \\
  \upsilon_{gt} &= \upsilon_0 + \alpha_{\upsilon} X_{\gamma} + \beta_{\upsilon} Z_{\gamma}
\end{align}

The parametric logit hazard for this component of the model is then,

\begin{equation}
  \text{logit} \left(\gamma_{gtd}\right) = \frac{p^{\prime}_{gtd}}{\left(1 -\sum^{d-1}_{d=0} p^{\prime}_{gtd} \right)}
\end{equation}

The non-distributional components for the date of occurance and report are then again defined using an intercept and arbitrary shared covariates with fixed ($\alpha_{i}$) and random ($\beta_{i}$) coefficients.

\begin{align}
  \delta_{gtd} &= \mu_0 + \alpha_{\delta} X_{\delta} + \beta_{\delta} Z_{\delta} \\
  \epsilon_{gtd} &= \epsilon_0 + \alpha_{\epsilon} X_{\epsilon} + \beta_{\epsilon} Z_{\epsilon}
\end{align}

The overall hazard for each group, occurance time, and delay is then,

\begin{equation}
  \text{logit} (h_{gtd}) = \gamma_{gtd} + \delta_{gtd} +  \upsilon_{gtd},\ h_{gtD} = 1
\end{equation}

and so the probability of report for a given delay, occurance date, and group is as follows.

\begin{equation}
  p_{gt0} = h_{gt0},\ p_{gtd} = \left(1 -\sum^{d-1}_{d=0} p_{gtd} \right) \times h_{gtd}
\end{equation}

All ($\alpha_{i}$) and random ($\beta_{i}$) coefficients have standard normal priors by default with standard half-normal priors for pooled standard deviations.

# Observation model and nowcast

Expected notifications by time of occurance ($t$) and reporting delay can now be found by multiplying expected final notifications for each $t$ with the probability of reporting for each day of delay ($p_{gtd}$). We then assume a negative binomial observation model with a joint overdispersion parameter (with a 1 over square root standard half normal prior) and produce a nowcast of final observed notifications at each occurance time by summing posterior estimates for each observed notification for that occurance time.

\begin{align}
  n_{gtd} \mid \lambda_{gt},p_{gtd}  &\sim \text{NB}(\lambda_{gt} \times p_{gtd}, \phi),\ t=1,...,T. \\
  \frac{1}{\phi^2} &\sim \text{Half-Normal}(0, 1) \\
  N_{gt} &= \sum_{d=0}^{D} n_{gtd}
\end{align}



# Implementation



# References
