name: Update contributors

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'cm-skip')"
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::allcontributors

      - name: Update contributors
        run: allcontributors::add_contributors(format = "text")
        shell: Rscript {0}
    
      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit README.* -m 'Update contributors [ci-skip]' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
