name: Update contributors

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::allcontributors

      - name: Update contributors
        run: allcontributors::add_contributors(format = "text")
        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.Rmd
          git diff-index --quiet HEAD || git commit -m "Automatic update of contributors"
          git pull --rebase origin ${{ github.ref.name }}
          git push origin || echo "No changes to push"
