on:
  push:
  workflow_dispatch:

name: Update contributors

jobs:
  render:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'cm-skip')"
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: NA
          extra-packages: any::allcontributors

      - name: Update contributors
        run: allcontributors::add_contributors(format = "text")
        shell: Rscript {0}
    
      - name: Commit results
        run: |
          git commit README.* -m 'Update contributors [ci-skip]' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
